name: Cross-OS Tests

on:
  push:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test:
    name: Run tests
    strategy:
      matrix:
#        os: [ubuntu-20.04]
#        node-version: [18]
        os:
        - ubuntu-22.04
        - ubuntu-20.04
#        - windows-latest
        - macos-latest
        node-version:
        - 14
        - 16
        - 18
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: cd tests && npm ci
    - run: cd tests && npm run test:ci
